name: StrengthSMP
version: '1.0.1'
main: com.myst1cs04p.strength_smp.Main
api-version: 1.16
commands:
  strength:
    description: View or set strength
    aliases: [str]
    usage: /<command> get|set|withdraw|help

permissions:
  strength.set:
    description: Allows setting player strength.
    default: op
  strength.get:
    description: Allows viewing strengths of players other than yourself
    default: op
  strength.reload:
    description: Reloads the plugin. Updates the plugin values to match the config.
    default: op