min-strength: -3
max-strength: 5
damage-multiplier: 0.3

strength-item:
  enabled: true
  recipe:
    key: strength_token
    shape:
      - "ABA"
      - "BCB"
      - "ADA"
    A: DIAMOND
    B: BLAZE_POWDER
    C: NETHER_STAR
    D: BLAZE_ROD
