name: StrengthSMP
version: '${version}'
main: com.myst1cs04p.strength_smp.bukkit.BukkitMain
api-version: '1.21'

commands:
  strength:
    description: View or manage strength
    aliases: [ str ]
    usage: /<command> <get|set|withdraw|reload|help|version>

permissions:
  strength.set:
    description: Allows setting player strength.
    default: op
  strength.get:
    description: Allows viewing other players' strength.
    default: op
  strength.reload:
    description: Reloads the plugin config.
    default: op
  strength.admin:
    description: Receives update nag messages on join.
    default: op
