name: StrengthSMP
version: '${version}'
api-version: '1.21'
main: com.myst1cs04p.strength_smp.paper.PaperMain
description: Strength SMP plugin - players gain and lose strength on PvP kills.
authors:
  - Myst1cS04p

bootstrapper: com.myst1cs04p.strength_smp.paper.StrengthBootstrapper

permissions:
  strength.set:
    description: Allows setting player strength.
    default: op
  strength.get:
    description: Allows viewing other players' strength.
    default: op
  strength.reload:
    description: Reloads the plugin config.
    default: op
  strength.version:
    description: Allows viewing the plugin version.
    default: op
  strength.admin:
    description: Receives update nag messages on join and scheduled broadcasts.
    default: op